0:
  press: 'touch ~/Desktop/x0.md'
  release: 'rm ~/Desktop/x0.md'
1:
  press: 'touch ~/Desktop/x1.md'
  release: 'rm ~/Desktop/x1.md'
2:
  press: 'touch ~/Desktop/x2.md'
  release: 'rm ~/Desktop/x2.md'
3:
  press: 'touch ~/Desktop/x3.md'
  release: 'rm ~/Desktop/x3.md'
4:
  press: 'touch ~/Desktop/x4.md'
  release: 'rm ~/Desktop/x4.md'
5:
  press: 'touch ~/Desktop/x5.md'
  release: 'rm ~/Desktop/x5.md'
6:
  press: 'touch ~/Desktop/x6.md'
  release: 'rm ~/Desktop/x6.md'
7:
  press: 'touch ~/Desktop/x7.md'
  release: 'rm ~/Desktop/x7.md'
8:
  press: 'touch ~/Desktop/x8.md'
  release: 'rm ~/Desktop/x8.md'
9:
  press: 'touch ~/Desktop/x9.md'
  release: 'rm ~/Desktop/x9.md'
10:
  press: 'touch ~/Desktop/x10.md'
  release: 'rm ~/Desktop/x10.md'
11:
  press: 'touch ~/Desktop/x11.md'
  release: 'rm ~/Desktop/x11.md'
12:
  press: 'touch ~/Desktop/x12.md'
  release: 'rm ~/Desktop/x12.md'
13:
  press: 'touch ~/Desktop/x13.md'
  release: 'rm ~/Desktop/x13.md'
14:
  press: 'touch ~/Desktop/x14.md'
  release: 'rm ~/Desktop/x14.md'
15:
  press: 'touch ~/Desktop/x15.md'
  release: 'rm ~/Desktop/x15.md'

