joy_driver:
  __ros_parameters:
    press:
        0: 'touch ~/Desktop/x0.md'
        1: 'touch ~/Desktop/x1.md'
        2: 'touch ~/Desktop/x2.md'
        3: 'touch ~/Desktop/x3.md'
        4: 'touch ~/Desktop/x4.md'
        5: 'touch ~/Desktop/x5.md'
        6: 'touch ~/Desktop/x6.md'
        7: 'touch ~/Desktop/x7.md'
        8: 'touch ~/Desktop/x8.md'
        9: 'touch ~/Desktop/x9.md'
        10: 'touch ~/Desktop/x10.md'
        11: 'touch ~/Desktop/x11.md'
        12: 'touch ~/Desktop/x12.md'
        13: 'touch ~/Desktop/x13.md'
        14: 'touch ~/Desktop/x14.md'
        15: 'touch ~/Desktop/x15.md'

    release:
        0: 'touch ~/Desktop/y0.md'
        1: 'touch ~/Desktop/y1.md'
        2: 'touch ~/Desktop/y2.md'
        3: 'touch ~/Desktop/y3.md'
        4: 'touch ~/Desktop/y4.md'
        5: 'touch ~/Desktop/y5.md'
        6: 'touch ~/Desktop/y6.md'
        7: 'touch ~/Desktop/y7.md'
        8: 'touch ~/Desktop/y8.md'
        9: 'touch ~/Desktop/y9.md'
        10: 'touch ~/Desktop/y10.md'
        11: 'touch ~/Desktop/y11.md'
        12: 'touch ~/Desktop/y12.md'
        13: 'touch ~/Desktop/y13.md'
        14: 'touch ~/Desktop/y14.md'
        15: 'touch ~/Desktop/y15.md'
