joy_driver:
  ros__parameters:
    action_modifier: 4
    press:
        0: 'touch ~/Desktop/x0.md'
        1: 'touch ~/Desktop/x1.md'
        2: 'touch ~/Desktop/x2.md'
        3: 'touch ~/Desktop/x3.md'
        4: ''
        5: 'touch ~/Desktop/x5.md'
        6: 'touch ~/Desktop/x6.md'
        7: 'touch ~/Desktop/x7.md'
        8: 'touch ~/Desktop/x8.md'
        9: 'touch ~/Desktop/x9.md'
        10: 'touch ~/Desktop/x10.md'
        11: 'touch ~/Desktop/x11.md'
        12: 'touch ~/Desktop/x12.md'
        13: 'touch ~/Desktop/x13.md'
        14: 'touch ~/Desktop/x14.md'
        15: 'touch ~/Desktop/x15.md'
    press_alt:
        0: 'wall="file:///$HOME/Pictures/Wallpapers/SHEEP.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        1: 'wall="file:///$HOME/Pictures/Wallpapers/AUSSIE.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        2: 'wall="file:///$HOME/Pictures/Wallpapers/BACK.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        3: 'wall="file:///$HOME/Pictures/Wallpapers/WHEAT.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        4: ''
        5: 'wall="file:///$HOME/Pictures/Wallpapers/YOUNG.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        6: 'touch ~/Desktop/y6.md'
        7: 'touch ~/Desktop/y7.md'
        8: ''
        9: 'cat $HOME/.gpass | xclip -selection clipboard'
        10: 'touch ~/Desktop/y10.md'
        11: 'touch ~/Desktop/y11.md'
        12: 'touch ~/Desktop/y12.md'
        13: 'touch ~/Desktop/y13.md'
        14: 'touch ~/Desktop/y14.md'
        15: 'touch ~/Desktop/y15.md'
    release:
        0: 'rm ~/Desktop/x0.md'
        1: 'rm ~/Desktop/x1.md'
        2: 'rm ~/Desktop/x2.md'
        3: 'rm ~/Desktop/x3.md'
        4: ''
        5: 'rm ~/Desktop/x5.md'
        6: 'rm ~/Desktop/x6.md'
        7: 'rm ~/Desktop/x7.md'
        8: 'rm ~/Desktop/y8.md'
        9: 'rm ~/Desktop/y9.md'
        10: 'rm ~/Desktop/x10.md'
        11: 'rm ~/Desktop/x11.md'
        12: 'rm ~/Desktop/x12.md'
        13: 'rm ~/Desktop/x13.md'
        14: 'rm ~/Desktop/x14.md'
        15: 'rm ~/Desktop/x15.md'
    release_alt:
        0: 'wall="file:///$HOME/Pictures/Wallpapers/COW.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        1: 'wall="file:///$HOME/Pictures/Wallpapers/COW.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        2: 'wall="file:///$HOME/Pictures/Wallpapers/COW.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        3: 'wall="file:///$HOME/Pictures/Wallpapers/COW.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        4: ''
        5: 'wall="file:///$HOME/Pictures/Wallpapers/COW.jpg"; gsettings set org.gnome.desktop.background picture-uri "$wall"; gsettings set org.gnome.desktop.background picture-uri-dark "$wall"'
        6: 'rm ~/Desktop/y6.md'
        7: 'rm ~/Desktop/y7.md'
        8: ''
        9: ''
        10: 'rm ~/Desktop/y10.md'
        11: 'rm ~/Desktop/y11.md'
        12: 'rm ~/Desktop/y12.md'
        13: 'rm ~/Desktop/y13.md'
        14: 'rm ~/Desktop/y14.md'
        15: 'rm ~/Desktop/y15.md'
